# Generated by Django 2.0.6 on 2018-06-19 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('cabin_number', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cabin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('persons', models.IntegerField()),
                ('title', models.CharField(default='', max_length=100)),
                ('short_description', models.CharField(default='', max_length=256)),
                ('long_description', models.CharField(default='', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='CabinImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='cabin',
            name='images',
            field=models.ManyToManyField(to='main.CabinImage'),
        ),
    ]
