# Generated by Django 2.0.6 on 2018-06-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180620_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinimage',
            name='img',
            field=models.ImageField(upload_to='cabins'),
        ),
    ]
