# Generated by Django 2.0.6 on 2018-06-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_cabinequipment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cabinequipment',
            old_name='equipment',
            new_name='eqp',
        ),
        migrations.AddField(
            model_name='cabin',
            name='equipment',
            field=models.ManyToManyField(blank=True, to='main.CabinEquipment'),
        ),
    ]
