# Generated by Django 2.0.6 on 2018-06-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180620_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabin',
            name='price',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
