# Generated by Django 2.0.6 on 2018-06-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20180621_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TentativeBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(verbose_name=50)),
                ('to_date', models.DateField()),
                ('cabin_number', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
