# Generated by Django 2.0.6 on 2018-06-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_bookingmanager_tentativebooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='late_arrival',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tentativebooking',
            name='from_date',
            field=models.DateField(),
        ),
    ]
