# Generated by Django 2.0.6 on 2018-07-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20180628_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='late_arrival',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tentativebooking',
            name='late_arrival',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
