# Generated by Django 2.0.6 on 2018-07-02 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20180702_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('late_arrival', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('cabins', models.ManyToManyField(to='main.Cabin')),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.ContactInfo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='booking',
            name='contact',
        ),
        migrations.DeleteModel(
            name='BookingManager',
        ),
        migrations.RemoveField(
            model_name='tentativebooking',
            name='cabin_number',
        ),
        migrations.AddField(
            model_name='tentativebooking',
            name='cabins',
            field=models.ManyToManyField(to='main.Cabin'),
        ),
        migrations.AlterField(
            model_name='tentativebooking',
            name='late_arrival',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
