# Generated by Django 2.0.6 on 2018-07-02 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0012_auto_20180702_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('late_arrival', models.BooleanField(default=False)),
                ('cabins', models.ManyToManyField(to='main.Cabin')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_main.booking_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.AlterModelOptions(
            name='finalbooking',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='tentativebooking',
            options={'base_manager_name': 'objects'},
        ),
        migrations.RemoveField(
            model_name='finalbooking',
            name='cabins',
        ),
        migrations.RemoveField(
            model_name='finalbooking',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='finalbooking',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='finalbooking',
            name='id',
        ),
        migrations.RemoveField(
            model_name='finalbooking',
            name='late_arrival',
        ),
        migrations.RemoveField(
            model_name='finalbooking',
            name='to_date',
        ),
        migrations.RemoveField(
            model_name='tentativebooking',
            name='cabins',
        ),
        migrations.RemoveField(
            model_name='tentativebooking',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='tentativebooking',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='tentativebooking',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tentativebooking',
            name='late_arrival',
        ),
        migrations.RemoveField(
            model_name='tentativebooking',
            name='to_date',
        ),
        migrations.AddField(
            model_name='finalbooking',
            name='booking_ptr',
            field=models.OneToOneField(auto_created=True, default=-1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Booking'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tentativebooking',
            name='booking_ptr',
            field=models.OneToOneField(auto_created=True, default=-1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Booking'),
            preserve_default=False,
        ),
    ]
