# Generated by Django 2.0.6 on 2018-07-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20180702_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabin',
            name='equivalent_cabins',
            field=models.ManyToManyField(blank=True, related_name='_cabin_equivalent_cabins_+', to='main.Cabin'),
        ),
    ]
