# Generated by Django 2.0 on 2018-07-04 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20180704_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=255)),
                ('late_arrival', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='finalbooking',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Contact'),
        ),
        migrations.DeleteModel(
            name='ContactInfo',
        ),
    ]
