# Generated by Django 2.0 on 2018-07-06 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20180705_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='late_arrival',
        ),
    ]
