# Generated by Django 2.0 on 2018-07-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_contact_late_arrival'),
    ]

    operations = [
        migrations.AddField(
            model_name='tentativebooking',
            name='last_updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
