# Generated by Django 2.0 on 2018-07-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_tentativebooking_last_updated_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cabin',
            options={'ordering': ['sort_presedence']},
        ),
        migrations.AddField(
            model_name='cabin',
            name='sort_presedence',
            field=models.IntegerField(default=-1),
        ),
    ]
