# Generated by Django 2.0 on 2018-07-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20180724_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_min_days_in_future', models.IntegerField(default=1, help_text='Min days from today that customer can book cabin.')),
            ],
        ),
    ]
