# Generated by Django 2.0 on 2018-07-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_adminsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='last_edit_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
