# Generated by Django 2.0 on 2018-07-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_adminsettings_last_edit_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminsettings',
            old_name='booking_min_days_in_future',
            new_name='min_from_date',
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='max_from_date',
            field=models.IntegerField(default=1, help_text='Max days from today that customer can book cabin.'),
        ),
    ]
