# Generated by Django 2.0 on 2018-07-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20180728_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='booking_close_time',
            field=models.TimeField(help_text='Time booking will close, if min_from_date is 0. (if customer can book today).', null=True),
        ),
    ]
