# Generated by Django 2.0 on 2018-07-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_adminsettings_booking_close_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminsettings',
            name='max_date_span',
            field=models.IntegerField(default=30, help_text='Max days for booking'),
        ),
    ]
